print('initial commit ')
print('second commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit')
print('last commit77')